### ISSUE TITLE
Install requirements for Goproformer

### ISSUE THREAD

**Issue by Alberto1995-Papaya** [amarda-shehu/GoProFormer#1]
Hi,

Does your Goproformer code have any requirements, such as a Pytorch version, .... ?
In the project files, I did not see any requirements file!

**Comment by akabiraka** [comment]
Thank you for reaching out.
The current pytorch, depending on the user's system requirements, should work.
The other packages we extensively utilized are: numpy, pandas, scikit-learn, matplotlib.

**Comment by Alberto1995-Papaya** [comment]
Thanks for your reply.
I had some problems with running your code in vscode and I thought the problem related to the compatibility versions of libraries like pytorch and I should be using a specific version for running your code.
My problem was solved and did not related to the library's versions.
